services:
    spark-master:
        build:
            context: .
            dockerfile: Dockerfile
        image: spark-extended:3.5.1
        container_name: spark-master
        restart: unless-stopped

        command: >
            /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
            --ip 0.0.0.0
            --port 7077
            --webui-port 8080

        env_file:
            - .env

        environment:
            SPARK_LOCAL_IP: 0.0.0.0
            SPARK_MASTER_WEBUI_PORT: 8080

            SPARK_DAEMON_MEMORY: 512m
            TZ: ${TZ}

        volumes:
            - ~/dataengineering/data:/data:z
            - ~/dataengineering/code:/code:z

            - ./spark-events:/opt/spark-events:z
            - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:z
        ports:
            - "8080:8080"
            - "7077:7077"

        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G

    spark-worker:
        image: spark-extended:3.5.1
        container_name: spark-worker
        restart: unless-stopped
        depends_on:
            - spark-master

        command: >
            /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
            spark://spark-master:7077

        env_file:
            - .env

        environment:
            SPARK_WORKER_WEBUI_PORT: 8081

            SPARK_LOCAL_IP: 0.0.0.0
            SPARK_WORKER_CORES: 1

            SPARK_WORKER_MEMORY: 4g
            SPARK_DAEMON_MEMORY: 512m

            TZ: ${TZ}

        volumes:
            - ~/dataengineering/data:/data:z
            - ~/dataengineering/code:/code:z

            - ./spark-events:/opt/spark-events:z
            - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:z

        ports:
            - "8081:8081"

        deploy:
            resources:
                limits:
                    cpus: "1.5"
                    memory: 5.5G

    spark-history-server:
        image: spark-extended:3.5.1
        container_name: spark-history-server
        restart: unless-stopped

        depends_on:
            - spark-master

        command: >
            /opt/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer

        env_file:
            - .env

        environment:
            SPARK_LOCAL_IP: 0.0.0.0
            SPARK_DAEMON_MEMORY: 512m

            TZ: ${TZ}

            SPARK_HISTORY_OPTS: >
                -Dspark.history.ui.port=18080
                -Dspark.history.fs.logDirectory=file:/opt/spark-events
                -Dspark.history.fs.cleaner.enabled=true
                -Dspark.history.fs.cleaner.maxAge=7d
                -Dspark.history.fs.cleaner.interval=1h

        volumes:
            - ./spark-events:/opt/spark-events:z
            - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:z

        ports:
            - "18080:18080"

        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G
