services:
  cassandra-seed:
    image: cassandra:5.0.6-jammy
    container_name: cassandra-seed
    hostname: cassandra-seed
    restart: unless-stopped

    ports:
      - "9042:9042"

    env_file:
      - .env

    environment:
      CASSANDRA_CLUSTER_NAME: "LearningCluster"
      CASSANDRA_SEEDS: ${TAILSCALE_IP}

      CASSANDRA_RPC_ADDRESS: 0.0.0.0
      CASSANDRA_BROADCAST_ADDRESS: ${TAILSCALE_IP}

      # Topology
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch

      MAX_HEAP_SIZE: ${CASSANDRA_MAX_HEAP}
      HEAP_NEWSIZE: ${CASSANDRA_HEAP_NEWSIZE}

      CASSANDRA_LISTEN_ADDRESS: auto

      TZ: ${TZ}

    volumes:
      - cassandra_seed_data:/var/lib/cassandra

    networks:
      - proj-net

  mysql:
    image: mysql:lts
    container_name: mysql
    restart: unless-stopped

    ports:
      - "3306:3306"

    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--max_connections=200",
        "--innodb_buffer_pool_size=512M",
      ]

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      MYSQL_DATABASE: ${MYSQL_DATABASE}

      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      TZ: ${TZ}

    volumes:
      - db-volume:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:Z
      - ./db/conf.d:/etc/mysql/conf.d:Z

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - proj-net

networks:
  proj-net:
    driver: bridge

volumes:
  db-volume:
  cassandra_seed_data:
  cassandra_node1_data:
