services:
  cassandra-seed:
    image: cassandra:5.0.6-jammy
    container_name: cassandra-seed
    hostname: cassandra-seed
    restart: unless-stopped

    ports:
      - "9042:9042"

    env_file:
      - .env

    environment:
      CASSANDRA_CLUSTER_NAME: "LearningCluster"
      CASSANDRA_SEEDS: cassandra-seed

      # Topology
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch

      MAX_HEAP_SIZE: ${CASSANDRA_MAX_HEAP}
      HEAP_NEWSIZE: ${CASSANDRA_HEAP_NEWSIZE}

      CASSANDRA_LISTEN_ADDRESS: auto
      CASSANDRA_RPC_ADDRESS: 0.0.0.0
      CASSANDRA_BROADCAST_RPC_ADDRESS: 100.124.171.81
      CASSANDRA_BROADCAST_ADDRESS: 100.124.171.81

      TZ: ${TZ}

    volumes:
      - cassandra_seed_data:/var/lib/cassandra

    networks:
      - proj-net

  cassandra-node-1:
    image: cassandra:5.0.6-jammy
    container_name: cassandra-node-1
    hostname: cassandra-node-1
    restart: unless-stopped
    depends_on:
      - cassandra-seed

    env_file:
      - .env

    environment:
      CASSANDRA_CLUSTER_NAME: "LearningCluster"
      CASSANDRA_SEEDS: cassandra-seed

      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch

      MAX_HEAP_SIZE: ${CASSANDRA_MAX_HEAP}
      HEAP_NEWSIZE: ${CASSANDRA_HEAP_NEWSIZE}

      TZ: ${TZ}

    volumes:
      - cassandra_node1_data:/var/lib/cassandra

    networks:
      - proj-net

  mysql:
    image: mysql:lts
    container_name: mysql
    restart: unless-stopped

    ports:
      - "3306:3306"

    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--max_connections=200",
        "--innodb_buffer_pool_size=512M",
      ]

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      MYSQL_DATABASE: ${MYSQL_DATABASE}

      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      CASSANDRA_LISTEN_ADDRESS: auto
      CASSANDRA_RPC_ADDRESS: 0.0.0.0
      CASSANDRA_BROADCAST_RPC_ADDRESS: 100.124.171.81
      CASSANDRA_BROADCAST_ADDRESS: 100.124.171.81

      TZ: ${TZ}

    volumes:
      - db-volume:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:Z
      - ./db/conf.d:/etc/mysql/conf.d:Z

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - proj-net

  # spark-master:
  #   image: apache/spark:3.5.1-scala2.12-java11-python3-ubuntu

  #   # user: "1000:1000"
  #   container_name: spark-master

  #   ports:
  #     - "8080:8080"
  #     - "7077:7077"

  #   env_file:
  #     - .env

  #   command: >
  #     /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
  #       --host spark-master

  #   environment:
  #     SPARK_MASTER_WEBUI_PORT: 8080

  #     SPARK_EVENTLOG_ENABLED: "true"
  #     SPARK_EVENTLOG_DIR: /opt/spark/logs

  #     SPARK_DRIVER_EXTRA_CLASSPATH: /opt/spark/jars_external/*
  #     SPARK_EXECUTOR_EXTRA_CLASSPATH: /opt/spark/jars_external/*

  #     TZ: ${TZ}

  #   volumes:
  #     - ./logs:/opt/spark/logs:z
  #     - ./data:/data:z
  #     - ./code:/code:z
  #     - ./jars:/opt/spark/jars_external:z

  #   networks:
  #     - proj-net

  # spark-worker-1:
  #   image: apache/spark:3.5.1-scala2.12-java11-python3-ubuntu

  #   # user: "1000:1000"
  #   container_name: spark-worker-1

  #   depends_on:
  #     - spark-master

  #   env_file:
  #     - .env

  #   ports:
  #     - "8081:8081"

  #   command: >
  #     /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
  #       --cores ${SPARK_WORKER_CORES}
  #       --memory ${SPARK_WORKER_MEMORY}
  #       spark://spark-master:7077

  #   environment:
  #     SPARK_WORKER_WEBUI_PORT: 8081

  #     SPARK_DRIVER_EXTRA_CLASSPATH: /opt/spark/jars_external/*
  #     SPARK_EXECUTOR_EXTRA_CLASSPATH: /opt/spark/jars_external/*

  #     TZ: ${TZ}

  #   volumes:
  #     - ./logs:/opt/spark/logs:z
  #     - ./data:/data:z
  #     - ./code:/code:z
  #     - ./jars:/opt/spark/jars_external:z

  #   networks:
  #     - proj-net

  # spark-worker-2:
  #   image: apache/spark:3.5.1-scala2.12-java11-python3-ubuntu

  #   # user: "1000:1000"
  #   container_name: spark-worker-2

  #   depends_on:
  #     - spark-master

  #   env_file:
  #     - .env

  #   ports:
  #     - "8082:8082"

  #   command: >
  #     /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
  #       --cores ${SPARK_WORKER_CORES}
  #       --memory ${SPARK_WORKER_MEMORY}
  #       spark://spark-master:7077

  #   environment:
  #     SPARK_WORKER_WEBUI_PORT: 8082

  #     SPARK_DRIVER_EXTRA_CLASSPATH: /opt/spark/jars_external/*
  #     SPARK_EXECUTOR_EXTRA_CLASSPATH: /opt/spark/jars_external/*

  #     TZ: ${TZ}

  #   volumes:
  #     - ./logs:/opt/spark/logs:z
  #     - ./data:/data:z
  #     - ./code:/code:z
  #     - ./jars:/opt/spark/jars_external:z

  #   networks:
  #     - proj-net

  # grafana:
  #   image: grafana/grafana:12.4.0-20733476222
  #   container_name: grafana

  #   user: "0"

  #   env_file:
  #     - .env

  #   ports:
  #     - "3000:3000"

  #   environment:
  #     TZ: ${TZ}

  #   volumes:
  #     - ./grafana:/var/lib/grafana:Z

  #   networks:
  #     - proj-net

networks:
  proj-net:
    driver: bridge

volumes:
  db-volume:
  cassandra_seed_data:
  cassandra_node1_data:
