CREATE TABLE recruitment.tracking (
    event_date    date,
    create_time   timeuuid,

    bid           float,
    bn            text,
    campaign_id   int,
    cd            int,
    custom_track  text,
    de            text,
    dl            text,
    dt            text,
    ed            text,
    ev            int,
    group_id      int,
    id            text,
    job_id        int,
    md            text,
    publisher_id  int,
    rl            text,
    sr            text,
    ts            text,
    tz            int,
    ua            text,
    uid           text,
    utm_campaign  text,
    utm_content   text,
    utm_medium    text,
    utm_source    text,
    utm_term      text,
    v             int,
    vp            text,

    PRIMARY KEY ((event_date), create_time)
) WITH CLUSTERING ORDER BY (create_time ASC);
