x-airflow-common: &airflow-common
    image: custom-airflow:2.8.1-python3.8
    build:
        context: .
        dockerfile: Dockerfile

    env_file:
        - .env

    environment: &airflow-common-env
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
        AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
        AIRFLOW__CORE__LOAD_EXAMPLES: "false"
        AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
        AIRFLOW_UID: ${AIRFLOW_UID}
        TZ: ${TZ}

        PYTHONPATH: /opt/project

        # --- LOGGING CỦA AIRFLOW (Text Log) ---
        AIRFLOW__LOGGING__REMOTE_LOGGING: "true"
        AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "s3://spark-log-proj/airflow-logs"
        AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "aws_default"
    volumes:
        # QUAN TRỌNG VỚI FEDORA/SELINUX: Thêm đuôi :z vào tất cả các dòng
        - ~/dataengineering/code/dags:/opt/airflow/dags:z
        - ./logs:/opt/airflow/logs:z
        - ./config:/opt/airflow/config:z
        - ./plugins:/opt/airflow/plugins:z
        - ~/dataengineering/code:/opt/project/code:z
        - ../spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:z

    user: "${AIRFLOW_UID}:0"
    depends_on: &airflow-common-depends-on
        postgres:
            condition: service_healthy

services:
    postgres:
        image: postgres:13
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "airflow" ]
            interval: 5s
            retries: 5
        restart: always

    airflow-webserver:
        <<: *airflow-common
        command: webserver
        ports:
            - "8080:8080"
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
            interval: 30s
            timeout: 30s
            retries: 5
        restart: always
        depends_on:
            <<: *airflow-common-depends-on
            airflow-init:
                condition: service_completed_successfully

    airflow-scheduler:
        <<: *airflow-common
        command: scheduler
        ports:
            - "30000:30000"
            - "30001:30001"
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost:8974/health" ]
            interval: 30s
            timeout: 30s
            retries: 5
        restart: always
        depends_on:
            <<: *airflow-common-depends-on
            airflow-init:
                condition: service_completed_successfully

    airflow-init:
        <<: *airflow-common
        entrypoint: /bin/bash

        user: "0:0"

        command:
            - -c
            - |
              mkdir -p /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins
              chown -R "1000:0" /opt/airflow/{logs,dags,plugins}
              exec /entrypoint airflow version

        environment:
            <<: *airflow-common-env
            _AIRFLOW_DB_MIGRATE: "true"
            _AIRFLOW_WWW_USER_CREATE: "true"
            _AIRFLOW_WWW_USER_USERNAME: airflow
            _AIRFLOW_WWW_USER_PASSWORD: airflow

volumes:
    postgres-db-volume:
