services:
  spark-master:
    image: apache/spark:3.5.1-scala2.12-java11-python3-ubuntu

    container_name: spark-master

    ports:
      - "8080:8080"
      - "7077:7077"

    env_file:
      - ../../.env

    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
        --host spark-master

    environment:
      SPARK_MASTER_WEBUI_PORT: 8080

      SPARK_EVENTLOG_ENABLED: "true"
      SPARK_EVENTLOG_DIR: /opt/spark/logs

      SPARK_DRIVER_EXTRA_CLASSPATH: /opt/spark/jars_external/*
      SPARK_EXECUTOR_EXTRA_CLASSPATH: /opt/spark/jars_external/*

      TZ: ${TZ}

    volumes:
      - ../../logs:/opt/spark/logs:z
      - ../../data:/data:z
      - ../../code:/code:z
      - ../../jars:/opt/spark/jars_external:z

    networks:
      - proj-net

  spark-worker-1:
    image: apache/spark:3.5.1-scala2.12-java11-python3-ubuntu

    container_name: spark-worker-1

    depends_on:
      - spark-master

    env_file:
      - ../../.env

    ports:
      - "8081:8081"

    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
        --cores ${SPARK_WORKER_CORES}
        --memory ${SPARK_WORKER_MEMORY}
        spark://spark-master:7077

    environment:
      SPARK_WORKER_WEBUI_PORT: 8081

      SPARK_DRIVER_EXTRA_CLASSPATH: /opt/spark/jars_external/*
      SPARK_EXECUTOR_EXTRA_CLASSPATH: /opt/spark/jars_external/*

      TZ: ${TZ}

    volumes:
      - ../../logs:/opt/spark/logs:z
      - ../../data:/data:z
      - ../../code:/code:z
      - ../../jars:/opt/spark/jars_external:z

    networks:
      - proj-net

  spark-worker-2:
    image: apache/spark:3.5.1-scala2.12-java11-python3-ubuntu

    container_name: spark-worker-2

    depends_on:
      - spark-master

    env_file:
      - ../../.env

    ports:
      - "8082:8082"

    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
        --cores ${SPARK_WORKER_CORES}
        --memory ${SPARK_WORKER_MEMORY}
        spark://spark-master:7077

    environment:
      SPARK_WORKER_WEBUI_PORT: 8082

      SPARK_DRIVER_EXTRA_CLASSPATH: /opt/spark/jars_external/*
      SPARK_EXECUTOR_EXTRA_CLASSPATH: /opt/spark/jars_external/*

      TZ: ${TZ}

    volumes:
      - ../../logs:/opt/spark/logs:z
      - ../../data:/data:z
      - ../../code:/code:z
      - ../../jars:/opt/spark/jars_external:z

    networks:
      - proj-net

  grafana:
    image: grafana/grafana:12.4.0-20733476222
    container_name: grafana

    user: "0"

    env_file:
      - ../.env

    ports:
      - "3000:3000"

    environment:
      TZ: ${TZ}

    volumes:
      - ../../grafana:/var/lib/grafana:Z

    networks:
      - proj-net

networks:
  proj-net:
    driver: bridge
